// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
require("chromedriver");
const assert = require('assert')

describe('LoginAndVerifyContactExperts', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('LoginAndVerifyContactExperts', async function() {
    await driver.get("https://apps.qa01.trustmineral-staging.com/auth/login/login")
    await driver.manage().window().setRect({ width: 1550, height: 838 })
    await driver.findElement(By.id("root_userCreds_username")).click()
    await driver.findElement(By.id("root_userCreds_username")).sendKeys("mayur_ta")
    await driver.findElement(By.id("root_userCreds_password")).click()
    await driver.findElement(By.id("root_userCreds_password")).sendKeys("Pepcusqa@23")
    await driver.findElement(By.css(".Button-sc-1v2whja-0")).click()
    await driver.wait(until.elementLocated(By.xpath("//p[text()=\'Which type of Expert do you want to contact?\']")), 30000)
    assert(await driver.findElement(By.xpath("//p[text()='Which type of Expert do you want to contact?']")).getText() == "Which type of Expert do you want to contact?")
    assert(await driver.findElement(By.xpath("//span[contains(text(),'Human Resources')]")).getText() == "Human Resources")
    assert(await driver.findElement(By.xpath("//span[contains(text(),'Employee Health & Safety')]")).getText() == "Employee Health & Safety")
  })
})
